// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDqOJCm7Lm9kf7fXyTv2YKY6Pm7XE6DjU',
    appId: '1:712628543956:web:53c2cab8dfceacc61db641',
    messagingSenderId: '712628543956',
    projectId: 'kk-info-sys',
    authDomain: 'kk-info-sys.firebaseapp.com',
    storageBucket: 'kk-info-sys.appspot.com',
    measurementId: 'G-QCSEV424ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ0bRykV0lAnQU3jbcGh-Sa91iMTR07zY',
    appId: '1:712628543956:android:009c3d073cbf57501db641',
    messagingSenderId: '712628543956',
    projectId: 'kk-info-sys',
    storageBucket: 'kk-info-sys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9q0bUKUYGkbzDF8eeaWtMXgjBNhopig',
    appId: '1:712628543956:ios:5a1e63b5810b9d801db641',
    messagingSenderId: '712628543956',
    projectId: 'kk-info-sys',
    storageBucket: 'kk-info-sys.appspot.com',
    iosBundleId: 'com.example.kkInformationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx9q0bUKUYGkbzDF8eeaWtMXgjBNhopig',
    appId: '1:712628543956:ios:5a1e63b5810b9d801db641',
    messagingSenderId: '712628543956',
    projectId: 'kk-info-sys',
    storageBucket: 'kk-info-sys.appspot.com',
    iosBundleId: 'com.example.kkInformationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDqOJCm7Lm9kf7fXyTv2YKY6Pm7XE6DjU',
    appId: '1:712628543956:web:dbbb2e93030f098a1db641',
    messagingSenderId: '712628543956',
    projectId: 'kk-info-sys',
    authDomain: 'kk-info-sys.firebaseapp.com',
    storageBucket: 'kk-info-sys.appspot.com',
    measurementId: 'G-6WNMY61SSP',
  );
}
